= ``mbox2m365``

== Abstract

This repository contains a simple python script that processes an ``mbox`` style mailbox file and parses out (typically) the last message and then re-transmits this using the CLI `m365` tools. While this script can be used in a completely stand-alone manner to extract a message from an ``mbox`` and then _send_ using ``m365``, it's main utility is when used in a full ecosystem including an email client and ``postfix`` server.

The CLI ``m365`` offers the ability to use Outlook/Office365 to send emails. However, this tool is not suited to use as a mail client -- it merely offers a means to transmit a message from the command line. More useful would be if existing mail clients could leverage ``m365`` natively. Currently, however, this is not available. Therefore, ``mbox2m365`` was created to complete a "missing link" in a full email experience. Using this tool in a configured environment, it is now possible to use _any_ email client to transmit messages using Outlook/Office365.

== TL;DR

Even if you're impatient, it's a good idea to read this document. However, assuming you've already built the infrastructure, assuming you have installed ``m365`` (and logged into your Institution from ``m365``), have assuming you have setup your email client to email to a dummy local postfix account, then you can install ``mbox2m365`` with a simple

```bash
pip install mbox2m365
```

and fire it off by setting up the monitor on the ``mbox`` file

```bash
cd /var/mail
find . | entr mbox2m365 --mbox rudolph
```



== Introduction

The migration/adoption of Office365 by institutions often poses issues and problems for users wishing to use different tools for email transmission, particularly on platforms such as Linux.

While it is possible to access various Office365 applications, particularly Outlook, via a web interface, this is often not sufficient for several classes of users, particularly those who find the web interface cumbersome (for instance, the web interface has no (or limited) support for keyboard shortcuts, it is cumbersome if not impossible to automate tasks involving event-driven email) and/or for users who have an existing and efficient email workflow using clients such as ``thunderbird`` or ``mutt``.

This small repo houses a small and simple python application with some supporting documentation that provides a solution to the problem of sending email from an instituion's managed domain by leveraging ``postfix`` and some ``mbox`` processing and then using the CLI tool ``m365``.

== Method Summary

The solution requires some seemingly contortuous steps, but in reality is rather simple and can be summarized as follows:

=== Reading email
Reading emails that are locked away in an Outlook server is best effected by simply adding a forward incoming email rule from your Institution Outlook Server (IOS) to an externally accessible email provider (such as ``gmail``), allowing this email to be read easily by tools such as ``thunderbird`` or ``mutt``.

```
┌─────────────────────────────────┐
│IOS that receives incoming email │
└┬────────────────────────────────┘
 │
 └─────┐
       │
      ┌O─────────────────────┐
      │forwardRule(<message>)│
      └┬─────────────────────┘
 ┌─────┘
 │
┌O────┐
│gmail│
└┬────┘
 └─────┐
       │
      ┌O──────────────────────┐
      │clientAccess(<message>)│
      └O──────────────────────┘
 ┌─────┘
 │
┌┴───────────────────────┐
│thunderbird / mutt / etc│
└────────────────────────┘

```


=== Sending email

The message is now outside of Outlook, and if the Institution does not allow non-authorized clients (often this means they only allow Microsoft tools) to connect to the Outlook server, the following work around will help. Essentially, the outside client should be configured to send email using a properly setup ``postfix`` server that simply copies the target email to an ``mbox`` file.

This ``mbox`` file is then monitored for any changes, and on a change (assumed to mean a new email message has been appended), a new process is fired off to parse off the latest message and then use the command line ``m365`` CLI tool to have the IOS send the email.

```
┌───────────────────────┐
│thundebird / mutt /etc │
└┬──────────────────────┘
 │
 └─────┐
       │
      ┌O────────────────────────────┐
      │sendmail(<message>) (postfix)│
      └┬────────────────────────────┘
 ┌─────┘
 │
┌O────┐
│mbox │
└┬────┘
 └─────┐
       │
      ┌O────────┐
      │mbox2m365│ <--- this repo!
      └┬────────┘
 ┌─────┘
 │
┌O─────────────┐
│m365 <message>│
└┬─────────────┘
 │
┌O────────────────────────────────┐
│IOS that transmits outgoing email│
└─────────────────────────────────┘
```

== Security alert!

Wait! Doesn't this violate security policies? Doesn't ``mbox2m365`` bypass instition authentication/etc? At first blush this might seem the case, however _no policy is violated_. All credentialing and authentication is handled by ``m365`` and _not_ this tool. The end user is still required to login/authenticate using ``m365``. If this has not happened, then ``mbox2m365`` will not work.

Again, this repo contains **no** authentication tokens/passwords/etc.

== ``mbox2m365``

While all the building blocks to effect the solution exist, the one missing piece is the ``mbox`` to ``m365`` block, which is provided for by this rather simple python script.



